/********************************************************************
* DihBsaDict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error DihBsaDict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableDihBsaDict();
extern void G__cpp_setup_inheritanceDihBsaDict();
extern void G__cpp_setup_typetableDihBsaDict();
extern void G__cpp_setup_memvarDihBsaDict();
extern void G__cpp_setup_globalDihBsaDict();
extern void G__cpp_setup_memfuncDihBsaDict();
extern void G__cpp_setup_funcDihBsaDict();
extern void G__set_cpp_environmentDihBsaDict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "Constants.h"
#include "Observable.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__DihBsaDictLN_TClass;
extern G__linked_taginfo G__DihBsaDictLN_TBuffer;
extern G__linked_taginfo G__DihBsaDictLN_TMemberInspector;
extern G__linked_taginfo G__DihBsaDictLN_TObject;
extern G__linked_taginfo G__DihBsaDictLN_vectorlEunsignedsPintcOallocatorlEunsignedsPintgRsPgR;
extern G__linked_taginfo G__DihBsaDictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__DihBsaDictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__DihBsaDictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__DihBsaDictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__DihBsaDictLN_vectorlETStringcOallocatorlETStringgRsPgR;
extern G__linked_taginfo G__DihBsaDictLN_reverse_iteratorlEvectorlETStringcOallocatorlETStringgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__DihBsaDictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__DihBsaDictLN_maplEstringcOTObjArraymUcOlesslEstringgRcOallocatorlEpairlEconstsPstringcOTObjArraymUgRsPgRsPgR;
extern G__linked_taginfo G__DihBsaDictLN_Observable;

/* STUB derived class for protected member access */
